/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.VeiculoDao;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import vo.VeiculoVo;

/**
 *
 * @author lukas
 */
public class TelaLista extends javax.swing.JFrame {

    /**
     * Creates new form TelaLista
     */
    public TelaLista() {
        initComponents();
    }
    
    private void carregaTabelaTxt(){
        try{
            DefaultTableModel modelo = (DefaultTableModel) tbVeiculo.getModel();
            
            if(modelo.getRowCount()> 0){
                modelo.setRowCount(0);
            }
            
            String projectDir = "\\Documents\\NetbeansProjects\\CadastroVeiculo";
            String dir = System.getProperty("user.home")+ projectDir;
            String nomeArquivo = "veiculo.txt";
            File arquivo = new File(dir, nomeArquivo);
            
            FileInputStream fis = new FileInputStream(arquivo);
            InputStreamReader isr = new InputStreamReader(fis);
            BufferedReader br = new BufferedReader(isr);
            
            String linha = br.readLine();
            while(linha!= null){
                Object[] obj = linha.split(";");
                modelo.addRow(obj);
                linha = br.readLine();
            }
            
        }catch(Exception e){
            e.getMessage();
        }
    }
    
    private void carregaTabela() throws SQLException{
 
        DefaultTableModel modelo = (DefaultTableModel) tbVeiculo.getModel();
        modelo.setNumRows(0);
        
        tbVeiculo.getColumnModel().getColumn(0).setPreferredWidth(20);
        tbVeiculo.getColumnModel().getColumn(1).setPreferredWidth(20);
        tbVeiculo.getColumnModel().getColumn(2).setPreferredWidth(20);
        tbVeiculo.getColumnModel().getColumn(3).setPreferredWidth(20);
        tbVeiculo.getColumnModel().getColumn(4).setPreferredWidth(20);
        
        VeiculoDao dao = new VeiculoDao();
        
        
        if(dao.carregaDados() == null){
            JOptionPane.showMessageDialog(null, "Não há dados para serem exibidos", "Atenção", JOptionPane.OK_OPTION);
        } else {
            for(VeiculoVo v : dao.carregaDados()){
            modelo.addRow(new Object[]{
                v.getNome(),
                v.getMarca(),
                v.getQtdPortas(),
                v.getCor(),
                v.getPlaca()
            });
        }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbVeiculo = new javax.swing.JTable();
        btnRefreshByTxt = new javax.swing.JButton();
        btnRefreshTable1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVoltarTela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tbVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Marca", "Nº Portas", "Cor", "Placa"
            }
        ));
        tbVeiculo.setCellSelectionEnabled(true);
        tbVeiculo.setRowHeight(20);
        jScrollPane1.setViewportView(tbVeiculo);

        btnRefreshByTxt.setText("Carregar Tabelo Pelo Txt");
        btnRefreshByTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshByTxtActionPerformed(evt);
            }
        });

        btnRefreshTable1.setText("Carregar Tabela pelo Banco");
        btnRefreshTable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTable1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Visualização dos dados");

        btnVoltarTela.setText("Voltar");
        btnVoltarTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarTelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRefreshTable1)
                                .addGap(18, 18, 18)
                                .addComponent(btnRefreshByTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVoltarTela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoltarTela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshByTxt)
                    .addComponent(btnRefreshTable1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshByTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshByTxtActionPerformed
        try {
            carregaTabelaTxt();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        } 
    }//GEN-LAST:event_btnRefreshByTxtActionPerformed

    private void btnRefreshTable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTable1ActionPerformed
        try {
            carregaTabela();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        } 
    }//GEN-LAST:event_btnRefreshTable1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        DefaultTableModel model = new DefaultTableModel();
        JTable table = new JTable(model);        // Cria duas colunas
        model.addColumn("Nome");
        model.addColumn("Marca");        // Muda o nome da primeira coluna
        model.addColumn("Nº Portas");        // Muda o nome da primeira coluna
        model.addColumn("Cor");        // Muda o nome da primeira coluna
        model.addColumn("Placa");        // Muda o nome da primeira coluna
    int vColIndex = 0;
    table.getColumnModel().getColumn(vColIndex).setHeaderValue("Novo Nome");        
    table.getTableHeader().resizeAndRepaint();
    }//GEN-LAST:event_formComponentShown

    private void btnVoltarTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTelaActionPerformed
        TelaCadastraVeiculo tcv = new TelaCadastraVeiculo();
        tcv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarTelaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshByTxt;
    private javax.swing.JButton btnRefreshTable1;
    private javax.swing.JButton btnVoltarTela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbVeiculo;
    // End of variables declaration//GEN-END:variables
}
